CREATE DATABASE PARQUEADERO
GO

USE PARQUEADERO
GO

CREATE TABLE VEHICULOS_MENSUALIDAD
(
  PLACA VARCHAR(6) PRIMARY KEY,
  MARCA VARCHAR(30) NOT NULL,
  MODELO VARCHAR(10) NOT NULL,
  COLOR VARCHAR(10) NOT NULL,
  NOMBRE_C VARCHAR(30) NOT NULL
)
GO
-- -----------------

CREATE TABLE VEHICULOS_EN_PARQUEADERO
(
  PLACA VARCHAR(6) PRIMARY KEY,
  COLOR VARCHAR(10) NOT NULL,
  FECHA DATETIME DEFAULT GETDATE(),
  MENSUALIDAD INT NOT NULL
)
GO
-- -----------------

CREATE FUNCTION fn_cupos_mensualidad()
RETURNS INT
AS 
BEGIN
  RETURN (SELECT COUNT(*)
  FROM VEHICULOS_MENSUALIDAD)
END
GO
-- -----------------

CREATE OR ALTER PROC sp_validar_mensualidad
  @PLACA VARCHAR(6),
  @COLOR VARCHAR(10) = NULL
AS
IF((SELECT COUNT(*)
FROM VEHICULOS_MENSUALIDAD
WHERE PLACA = @PLACA) = 1)
  BEGIN
  IF((SELECT COLOR
    FROM VEHICULOS_MENSUALIDAD
    WHERE PLACA = @PLACA) <> @COLOR AND @COLOR IS NOT NULL)
    BEGIN
    UPDATE VEHICULOS_MENSUALIDAD SET COLOR = @COLOR WHERE PLACA = @PLACA
  END
  SELECT 1
END
ELSE
  BEGIN
  SELECT 0
END
GO
-- -----------------

CREATE FUNCTION fn_verificar_vehiculo_parqueadero(@PLACA VARCHAR(6))
RETURNS INT
AS 
BEGIN
  RETURN (SELECT COUNT(*)
  FROM VEHICULOS_EN_PARQUEADERO
  WHERE PLACA = @PLACA)
END
GO
-- -----------------

CREATE FUNCTION fn_cupos_parqueadero()
RETURNS INT
AS 
BEGIN
  RETURN ((SELECT COUNT(*)
  FROM VEHICULOS_EN_PARQUEADERO
  WHERE MENSUALIDAD = 0
  ) + dbo.fn_cupos_mensualidad())
END
GO
-- -----------------

CREATE PROC sp_total_pagar
  @PLACA VARCHAR(6)
AS
DECLARE @FECHA DATETIME, @PRECIO DECIMAL(10,0)
SET @FECHA = (SELECT FECHA
FROM VEHICULOS_EN_PARQUEADERO
WHERE PLACA = @PLACA)

SET @PRECIO = (DATEDIFF(MINUTE, @FECHA, GETDATE()) + 1) * 1000
SELECT @PRECIO
GO
-- -----------------
